### ISSUE TITLE
Strange Highlighting?

### ISSUE THREAD

**Issue by gholt** [msoap/go-carpet#14]
This may be my environments or "something" but the highlighting seems to be in odd places occasionally. Some output I'm looking at now has a line with the text `return typedValue` and half the line is not highlighted and half is, as in <pre>return type**dValue**</pre> (imagine the bold is green).

**Comment by gholt** [comment]
Oh, I should note that this could be because of the Go Modules scenario I'm working under right now. When I next work in an oldschool GOPATH/src scenario I'll pay attention to whether this happens then too.

**Comment by gholt** [comment]
Ignore this. It turns out I had the code in the Go Modules setup (outside the GOPATH) **and** I had a copy of the code in the GOPATH from some earlier debugging I was doing. Once I cleared out the code in the GOPATH, the Go Modules scenario had perfect highlighting again (since the source code actually matched).

Sorry for the noise. :)

**Comment by msoap** [comment]
> Sorry for the noise. :)

np :)
