### ISSUE TITLE
Go Modules Support

### ISSUE THREAD

**Issue by gholt** [msoap/go-carpet#15]
Sorry for the repeat. :)
Turns out the quick fix I did to work with Go Modules style code directories wasn't quite exact.
It seems to work fine in the root of the go.mod enabled repo, but not in subdirs/packages.
My first guess is that the code will need to look for go.mod in the current and parent directories to determine the source file paths.
I don't quite have time to mess with it _right now_; hence this issue in case someone does have time before me.

**Comment by msoap** [comment]
I think this problem can be solved by parsing the output of `go env GOMOD`, it works in any sub-directory.

**Comment by gholt** [comment]
Oh, sheesh, I didn't even notice GOMOD was an option. :)
