### ISSUE TITLE
Option to exclude directory

### ISSUE THREAD

**Issue by jcscottiii** [msoap/go-carpet#2]
Instead of specifying all the directories to include, it would be nice to have the option to just specify the directories to exclude. For example, if I have vendored code in `Godeps/`, I could just specify to exclude the Godeps folder but run on everything else.

**Comment by msoap** [comment]
Or another option. May be exclude by default Godeps/ and vendor/, and option -include-vendor?

**Comment by jcscottiii** [comment]
That works too!

**Comment by msoap** [comment]
Fixed in https://github.com/msoap/go-carpet/commit/365c196c007206213bd338a7b2ff89ce608ae24e

**Comment by msoap** [comment]
Sorry, real fixed in https://github.com/msoap/go-carpet/commit/2e020eec7ba047881ac360003e035c7e67678ba8
