### ISSUE TITLE
Coverage stats

### ISSUE THREAD

**Issue by matrixik** [msoap/go-carpet#5]
Just some random idea:
maybe you can add coverage stats to each file and at the end show average coverage for all files or by package etc. (weighted, taking into account number of lines in each file).
Something like you can see on gocover: https://gocover.io/github.com/msoap/go-carpet

Cheers

**Comment by msoap** [comment]
Statistics by package can be obtained through run:
`go test -cover ./...`

Show average coverage stats for all files is a good idea.
maybe = all covered lines/(all uncovered+all covered lines)

**Comment by msoap** [comment]
Added stat by file and total stat in https://github.com/msoap/go-carpet/commit/a0fdcf02d6ddd02d44bb97c5f78aa8d411d4037e, https://github.com/msoap/go-carpet/commit/b4edf849e4d8172ed0d6fa1aae81b20a9947c829

**Comment by matrixik** [comment]
Working great. Thank you.
